/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <android/log.h>
/* Header for class com_xinlan_jnicreate_NativeLib */

#ifndef _Included_com_xinlan_jnicreate_NativeLib
#define _Included_com_xinlan_jnicreate_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinlan_jnicreate_NativeLib
 * Method:    createStudent
 * Signature: (Ljava/lang/String;IC)Lcom/xinlan/jnicreate/model/Student;
 */
JNIEXPORT jobject JNICALL Java_com_xinlan_jnicreate_NativeLib_createStudent
  (JNIEnv *, jclass, jstring, jint, jchar);

JNIEXPORT jobject JNICALL Java_com_xinlan_jnicreate_NativeLib_parseJSON
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
